# Generated by Django 4.0.3 on 2022-04-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_info_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='perce',
            field=models.FloatField(),
        ),
    ]
