# Generated by Django 4.0.3 on 2022-04-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_skills_perce'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='category_filter',
            field=models.CharField(choices=[('web', 'web'), ('rest', 'rest'), ('design', 'design')], default='web', max_length=100),
        ),
    ]
